# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CovidCases' do
  platform :ios, '12.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CovidCases
  pod 'Alamofire', '~> 4.7.2'
  pod 'R.swift', '~> 5.1.0'

  target 'CovidCasesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      if ['Alamofire'].include? target.name
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_VERSION'] = '4.2'
          end
      end
  end

  # This removes the warning about swift conversion
   installer.pods_project.root_object.attributes['LastSwiftMigration'] = 9999
   installer.pods_project.root_object.attributes['LastSwiftUpdateCheck'] = 9999
   installer.pods_project.root_object.attributes['LastUpgradeCheck'] = 9999
end
