# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CoronaCases' do
  platform :ios, '12.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoronaCases
  pod 'Alamofire'

  target 'CoronaCasesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
